import { FormEvent, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getTboMasterHotel, previewTboMasterPrice, TboMasterHotel, TboMasterReview, updateTboMasterHotel } from "@/services/tboMasterHotels";

type EditorState = {
  name: string; address: string; city: string; rating: number; imageUrl: string;
  description: string; checkInTime: string; checkOutTime: string; facilities: string;
  amenities: string; latitude: string; longitude: string; status: number;
};

const editorFromHotel = (hotel: TboMasterHotel): EditorState => ({
  name: hotel.name || "", address: hotel.address || "", city: hotel.city || "",
  rating: Number(hotel.rating || 0), imageUrl: hotel.imageUrl || "",
  description: hotel.description || "", checkInTime: hotel.checkInTime || "",
  checkOutTime: hotel.checkOutTime || "", facilities: (hotel.facilities || []).join(", "),
  amenities: (hotel.amenities || []).join(", "), latitude: hotel.latitude == null ? "" : String(hotel.latitude),
  longitude: hotel.longitude == null ? "" : String(hotel.longitude), status: Number(hotel.status) === 1 ? 1 : 0,
});
const splitList = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

export default function TboMasterHotelDetail() {
  const { code = "" } = useParams();
  const [hotel, setHotel] = useState<TboMasterHotel | null>(null); const [form, setForm] = useState<EditorState | null>(null);
  const [reviews, setReviews] = useState<TboMasterReview[]>([]); const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const [priceForm, setPriceForm] = useState({ checkIn: "", checkOut: "", rooms: 1, adults: 2, children: 0, mealPlanCode: "" });
  const [priceLoading, setPriceLoading] = useState(false); const [priceResult, setPriceResult] = useState<any>(null);

  useEffect(() => { getTboMasterHotel(code).then((value) => { setHotel(value); setForm(editorFromHotel(value)); setReviews(value.reviews || []); }).catch((err) => setMessage(err?.message || "Unable to load hotel")).finally(() => setLoading(false)); }, [code]);
  if (loading) return <div className="p-8">Loading VSR master hotel…</div>;
  if (!hotel || !form) return <div className="p-8 text-red-700">{message || "Hotel not found"}</div>;
  const setField = <K extends keyof EditorState>(field: K, value: EditorState[K]) => setForm((current) => current ? { ...current, [field]: value } : current);
  const save = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); try { const updated = await updateTboMasterHotel(code, { name: form.name, address: form.address, city: form.city, rating: form.rating, imageUrl: form.imageUrl, description: form.description, checkInTime: form.checkInTime, checkOutTime: form.checkOutTime, facilities: splitList(form.facilities), amenities: splitList(form.amenities), latitude: form.latitude, longitude: form.longitude, status: form.status, reviews }); setHotel(updated); setForm(editorFromHotel(updated)); setReviews(updated.reviews || []); setMessage("All VSR master details saved."); } catch (err: any) { setMessage(err?.message || "Unable to save"); } finally { setSaving(false); } };
  const runPricePreview = async (event: FormEvent) => { event.preventDefault(); setPriceLoading(true); setPriceResult(null); try { setPriceResult(await previewTboMasterPrice(code, priceForm)); } catch (err: any) { setPriceResult({ status: "ERROR", message: err?.message || "Unable to load live price" }); } finally { setPriceLoading(false); } };
  const inputClass = "mt-1 w-full rounded border p-2";
  return <div className="min-h-screen bg-white p-6 md:p-8"><div className="mb-6 flex items-center justify-between gap-4"><div><Link className="text-sm text-violet-700" to="/hotels/tbo-master">← VSR Master Hotels</Link><h1 className="mt-2 text-2xl font-semibold text-slate-800">{hotel.name}</h1><p className="font-mono text-xs text-slate-500">{hotel.hotelCode} · {hotel.cityCode}</p></div><div className="rounded-md border px-3 py-2 text-sm">Priority: <strong>{hotel.isPriority ? "Yes" : "No"}</strong></div></div>
    {message && <div className="mb-4 rounded-md border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{message}</div>}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(360px,1fr)]"><form onSubmit={save} className="space-y-5 rounded-lg border p-5"><h2 className="text-lg font-semibold">Master content</h2><p className="text-xs text-slate-500">VSR code and city code are source identifiers and remain read-only.</p><div className="grid gap-3 md:grid-cols-2">
      <label className="text-sm font-medium md:col-span-2">Hotel name<input className={inputClass} value={form.name} onChange={(e) => setField("name", e.target.value)} /></label><label className="text-sm font-medium">VSR hotel code<input className={`${inputClass} bg-slate-100`} value={hotel.hotelCode} readOnly /></label><label className="text-sm font-medium">VSR city code<input className={`${inputClass} bg-slate-100`} value={hotel.cityCode} readOnly /></label><label className="text-sm font-medium">City<input className={inputClass} value={form.city} onChange={(e) => setField("city", e.target.value)} /></label><label className="text-sm font-medium">Star rating<input className={inputClass} type="number" min={0} max={5} value={form.rating} onChange={(e) => setField("rating", Number(e.target.value))} /></label><label className="text-sm font-medium md:col-span-2">Address<textarea className={inputClass} value={form.address} onChange={(e) => setField("address", e.target.value)} /></label><label className="text-sm font-medium md:col-span-2">Image URL<input className={inputClass} value={form.imageUrl} onChange={(e) => setField("imageUrl", e.target.value)} /></label><label className="text-sm font-medium">Check-in time<input className={inputClass} value={form.checkInTime} onChange={(e) => setField("checkInTime", e.target.value)} /></label><label className="text-sm font-medium">Check-out time<input className={inputClass} value={form.checkOutTime} onChange={(e) => setField("checkOutTime", e.target.value)} /></label><label className="text-sm font-medium">Latitude<input className={inputClass} value={form.latitude} onChange={(e) => setField("latitude", e.target.value)} /></label><label className="text-sm font-medium">Longitude<input className={inputClass} value={form.longitude} onChange={(e) => setField("longitude", e.target.value)} /></label><label className="text-sm font-medium">Status<select className={inputClass} value={form.status} onChange={(e) => setField("status", Number(e.target.value))}><option value={1}>Active</option><option value={0}>Inactive</option></select></label></div>
      <label className="block text-sm font-medium">Description<textarea className="mt-1 min-h-28 w-full rounded border p-2" value={form.description} onChange={(e) => setField("description", e.target.value)} /></label><label className="block text-sm font-medium">Facilities <span className="font-normal text-slate-500">(comma separated)</span><textarea className="mt-1 min-h-20 w-full rounded border p-2" value={form.facilities} onChange={(e) => setField("facilities", e.target.value)} /></label><label className="block text-sm font-medium">Amenities <span className="font-normal text-slate-500">(comma separated)</span><textarea className="mt-1 min-h-20 w-full rounded border p-2" value={form.amenities} onChange={(e) => setField("amenities", e.target.value)} /></label>
      <div><div className="mb-2 flex items-center justify-between"><h3 className="font-medium">Reviews</h3><button type="button" className="rounded border px-2 py-1 text-xs" onClick={() => setReviews([...reviews, { rating: 5, title: "", comment: "", author: "" }])}>Add review</button></div>{reviews.map((review, index) => <div className="mb-2 grid gap-2 rounded border p-2 md:grid-cols-4" key={index}><input className="rounded border p-2" placeholder="Rating" type="number" min={1} max={5} value={review.rating ?? ""} onChange={(e) => setReviews(reviews.map((item, i) => i === index ? { ...item, rating: Number(e.target.value) } : item))} /><input className="rounded border p-2" placeholder="Title" value={review.title || ""} onChange={(e) => setReviews(reviews.map((item, i) => i === index ? { ...item, title: e.target.value } : item))} /><input className="rounded border p-2 md:col-span-2" placeholder="Comment" value={review.comment || ""} onChange={(e) => setReviews(reviews.map((item, i) => i === index ? { ...item, comment: e.target.value } : item))} /><input className="rounded border p-2" placeholder="Author" value={review.author || ""} onChange={(e) => setReviews(reviews.map((item, i) => i === index ? { ...item, author: e.target.value } : item))} /><button type="button" className="text-left text-xs text-red-600" onClick={() => setReviews(reviews.filter((_, i) => i !== index))}>Remove review</button></div>)}</div><button disabled={saving} className="rounded bg-violet-600 px-4 py-2 text-white disabled:opacity-50">{saving ? "Saving…" : "Save all master details"}</button></form>
      <form onSubmit={runPricePreview} className="h-fit space-y-4 rounded-lg border p-5"><h2 className="text-lg font-semibold">Live VSR price preview</h2><p className="text-sm text-slate-500">Prices are fetched only when requested and are not stored in the master record.</p><div className="grid gap-3 md:grid-cols-2"><label className="text-sm">Check-in<input required type="date" className={inputClass} value={priceForm.checkIn} onChange={(e) => setPriceForm({ ...priceForm, checkIn: e.target.value })} /></label><label className="text-sm">Check-out<input required type="date" className={inputClass} value={priceForm.checkOut} onChange={(e) => setPriceForm({ ...priceForm, checkOut: e.target.value })} /></label><label className="text-sm">Rooms<input min={1} type="number" className={inputClass} value={priceForm.rooms} onChange={(e) => setPriceForm({ ...priceForm, rooms: Number(e.target.value) })} /></label><label className="text-sm">Adults<input min={1} type="number" className={inputClass} value={priceForm.adults} onChange={(e) => setPriceForm({ ...priceForm, adults: Number(e.target.value) })} /></label><label className="text-sm">Children<input min={0} type="number" className={inputClass} value={priceForm.children} onChange={(e) => setPriceForm({ ...priceForm, children: Number(e.target.value) })} /></label><label className="text-sm">Meal plan<input className={inputClass} placeholder="Optional" value={priceForm.mealPlanCode} onChange={(e) => setPriceForm({ ...priceForm, mealPlanCode: e.target.value })} /></label></div><button disabled={priceLoading} className="rounded bg-slate-800 px-4 py-2 text-white disabled:opacity-50">{priceLoading ? "Checking VSR…" : "Check live prices"}</button>{priceResult && <div className={`rounded border p-3 text-sm ${priceResult.status === "AVAILABLE" ? "border-green-200 bg-green-50" : "border-amber-200 bg-amber-50"}`}><strong>{priceResult.status}</strong>{priceResult.message && <p className="mt-1">{priceResult.message}</p>}{priceResult.options?.map((option: any, index: number) => <div className="mt-3 border-t pt-2" key={index}><b>{option.roomType || "Room"}</b> · {option.mealPlan || "—"}<p>₹ {Number(option.totalStayPrice ?? option.price ?? 0).toLocaleString("en-IN")}</p></div>)}</div>}</form></div></div>;
}

